# Generated by Django 2.2.2 on 2021-08-24 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
