# Generated by Django 2.2.2 on 2021-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210824_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='q_id',
        ),
    ]
