# Generated by Django 2.2.2 on 2019-06-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_id', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
    ]
