# Generated by Django 2.2.2 on 2019-06-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=10)),
                ('topicname', models.CharField(max_length=100)),
                ('content', models.FileField(null=True, upload_to='')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Subject')),
            ],
            options={
                'verbose_name_plural': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField()),
                ('q_text', models.CharField(max_length=300)),
                ('a', models.CharField(max_length=300)),
                ('b', models.CharField(max_length=300)),
                ('c', models.CharField(max_length=300)),
                ('d', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Subject')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Topic')),
            ],
            options={
                'verbose_name_plural': 'Question',
            },
        ),
    ]
