# Generated by Django 2.2.2 on 2019-06-29 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_questions_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='e',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
