# Generated by Django 2.2.2 on 2021-03-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_extendeduser_otpregistration_testquestions_testrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='new.Subject'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='new.Topic'),
        ),
    ]
